Fix SF #3036369:
With Python 2.7, DistutilsOptionError was removed from distutils.core,
though it still officially remains in distutils.errors. This causes
comtypes to not install properly. Instead, an error similar to the
following is generated:

\comtypes> .\setup.py
Traceback (most recent call last):
  File "\comtypes\setup.py", line 42, in <module>
    from distutils.core import setup, Command, DistutilsOptionError
ImportError: cannot import name DistutilsOptionError

Patch by Jason R. Coombs.